version: 0.0
os: linux
files:
 - source: .
   destination: /home/ubuntu/app
hooks:
  AfterInstall:
   - location: install_app_dependencies
     timeout: 300
     runas: root
  ApplicationStart:
   - location: start_server
     timeout: 300
     runas: root
  ApplicationStop:
    - location: stop_server
      timeout: 300
      runas: root