name: Super-Linter

on:  
  push:
  pull_request:
    branches:
      - master

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Running script from repo
        run: sh ./sample.sh
        
        
