name: Artifacts-demo

on:  
  push:
    branches:
      - master

jobs:
  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Creating folder
        run: mkdir config
        
      - name: publishin artifacts to folder
        run: | 
          cd  config
          echo 'first' > first.html
          echo 'second' >second.html
          cd ..
      - name:  using upload artifacts  gihub action
        uses: actions/upload-artifacts@v2
        with: 
          name: files-for-download
          path: config
        
        
